<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ColorPaletteController;
use App\Http\Controllers\PngToSvgController;
use App\Http\Controllers\ImageCompressorController;
use App\Http\Controllers\ImageCropperController;
use App\Http\Controllers\QrCodeController;
use App\Http\Controllers\PasswordGeneratorController;
use App\Http\Controllers\HashGeneratorController;
use App\Http\Controllers\Base64Controller;
use App\Http\Controllers\JsonFormatterController;
use App\Http\Controllers\WordCounterController;
use App\Http\Controllers\UuidGeneratorController;
use App\Http\Controllers\LoremIpsumController;
use App\Http\Controllers\ColorPickerController;
use App\Http\Controllers\ImagesToPdfController;
use App\Http\Controllers\PdfCompressorController;
use App\Http\Controllers\WordToPdfController;
use App\Http\Controllers\PdfToWordController;
use App\Http\Controllers\DiffCheckerController;
use App\Http\Controllers\RegexTesterController;
use App\Http\Controllers\TimestampController;
use App\Http\Controllers\JwtDecoderController;
use App\Http\Controllers\MarkdownController;

Route::get('/', [DashboardController::class, 'index']);
Route::get('/color-palette', [ColorPaletteController::class, 'index']);
Route::get('/png-to-svg', [PngToSvgController::class, 'index']);
Route::get('/image-compressor', [ImageCompressorController::class, 'index']);
Route::get('/image-cropper', [ImageCropperController::class, 'index']);
Route::get('/qr-code', [QrCodeController::class, 'index']);
Route::get('/password-generator', [PasswordGeneratorController::class, 'index']);
Route::get('/hash-generator', [HashGeneratorController::class, 'index']);
Route::get('/base64', [Base64Controller::class, 'index']);
Route::get('/json-formatter', [JsonFormatterController::class, 'index']);
Route::get('/word-counter', [WordCounterController::class, 'index']);
Route::get('/uuid-generator', [UuidGeneratorController::class, 'index']);
Route::get('/lorem-ipsum', [LoremIpsumController::class, 'index']);
Route::get('/color-picker', [ColorPickerController::class, 'index']);
Route::get('/images-to-pdf', [ImagesToPdfController::class, 'index']);
Route::get('/pdf-compressor', [PdfCompressorController::class, 'index']);
Route::get('/word-to-pdf', [WordToPdfController::class, 'index']);
Route::get('/pdf-to-word', [PdfToWordController::class, 'index']);
Route::get('/diff-checker', [DiffCheckerController::class, 'index']);
Route::get('/regex-tester', [RegexTesterController::class, 'index']);
Route::get('/timestamp', [TimestampController::class, 'index']);
Route::get('/jwt-decoder', [JwtDecoderController::class, 'index']);
Route::get('/markdown', [MarkdownController::class, 'index']);
